# Generated by Django 6.1.1 on 2026-09-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='joined_at',
        ),
        migrations.AddField(
            model_name='projectmember',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='left_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
